language: go

go:
  - 1.12.7

before_install:
- export GO111MODULE='on'
- export CGO_CFLAGS="-g -O2 -std=gnu99"
- echo "installing entangled dependencies"
- sudo apt-get install -y xsltproc
- wget https://github.com/bazelbuild/bazel/releases/download/0.28.0/bazel_0.28.0-linux-x86_64.deb
- sudo dpkg -i bazel_0.28.0-linux-x86_64.deb
- git submodule update --init --recursive
- echo "building MAM linux 64-bit shared library..."
- cd x/mam/entangled && bazel build --copt='-std=c99' -c opt //mam:libmam.so
- sudo cp bazel-bin/mam/libmam.so /usr/lib
- sudo cp bazel-bin/mam/libmam.so ./../
- cd ./../XKCP
- echo "building keccak linux 64-bit shared library..."
- make generic64/libkeccak.so
- sudo cp bin/generic64/libkeccak.so /usr/lib
- sudo cp bin/generic64/libkeccak.so ./../
- cd ./../
- mv libmam.so libmam_linux_x64.so
- sha256sum libmam_linux_x64.so
- mv libkeccak.so libkeccak_linux_x64.so
- sha256sum libkeccak_linux_x64.so
- echo "creating tar containing headers for MAM"
- tar -czf headers.tar keccak mam uthash
- cd ./../../
- echo "successfully built MAM dependencies"
- go get -u github.com/mgechev/revive
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega/...
- export PATH=$PATH:$GOPATH/bin
- export CGO_LDFLAGS_ALLOW='-msse2,-mavx'
- export CGO_CFLAGS_ALLOW='-msse2,-mavx'
- go get ./...

script:
- ginkgo -tags="pow_avx pow_sse pow_c pow_c128" -r --skipPackage=mongo --randomizeSuites --failOnPending --cover --progress

after_success:
- revive -config revive.toml -formatter stylish -exclude ./api/integration/... ./...

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - libmam_linux_x64.so
      - libkeccak_linux_x64.so
      - headers.tar
    skip_cleanup: true
    on:
      tags: true